name: Test LinkedIn Auto Poster

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  test-linkedin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests schedule pytz

    - name: Test Raindrop Fetch
      run: |
        python -c "from raindrop_fetcher import fetch_raindrop_bookmarks; print(fetch_raindrop_bookmarks(limit=2))"

    - name: Test Perplexity Generation
      run: |
        python -c "from raindrop_fetcher import fetch_raindrop_bookmarks; from perplexity_generator import generate_ideas; bms=fetch_raindrop_bookmarks(limit=1); print(generate_ideas(bms[0]))"

    - name: Test LinkedIn Post (Dry Run)
      env:
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        LINKEDIN_PAGE_URN: ${{ secrets.LINKEDIN_PAGE_URN }}
      run: |
        echo "✅ Dry run: Would post to LinkedIn page $LINKEDIN_PAGE_URN"
        # Uncomment below to actually post (use with caution)
        # python -c "from linkedin_poster import post_linkedin; post_linkedin('Test post from GitHub Actions')"
